name: Deploy Hugo Site to Github Pages on Master Branch

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
       # with:
       #   submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # 这里的 ACTIONS_DEPLOY_KEY 则是上面设置 Private Key的变量名
          external_repository: Rurouni-z/Rurouni-z.github.io # Pages 远程仓库 
          publish_dir: "./public"
          keep_files: true # remove existing files
          publish_branch: build  # deploying branch
          commit_message: ${{ github.event.head_commit.message }}
        
      - name: Push yaml to another repository
        uses: nkoppel/push-files-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: '.github/workflows/upload_algolia.yaml'
          destination-username: 'Rurouni-z'
          destination-repository: 'Rurouni-z.github.io'
          destination-directory: ' .github/workflows'
          destination-branch: 'build'
          commit-email: 'upload algolia action'
